Meteor.subscribe("projects");
Meteor.subscribe("opportunities");
Meteor.subscribe("companies");
Meteor.subscribe("contacts");
Meteor.subscribe("project_roles");
Meteor.subscribe("rate_book_roles");
rateBooksSubscriptionHandle = Meteor.subscribe("rate_books");
Meteor.subscribe("roles");
Meteor.subscribe("skills");
//Meteor.subscribe("users");
Meteor.subscribe("fields");
