projectsSubscriptionHandle = Meteor.subscribe("projects");
opportunitiesSubscriptionHandle = Meteor.subscribe("opportunities");
companiesSubscriptionHandle = Meteor.subscribe("companies");
Meteor.subscribe("contacts");
projectRolesSubscriptionHandle = Meteor.subscribe("project_roles");
Meteor.subscribe("project_role_skills");
Meteor.subscribe("project_role_schedule");
projectRoleResourcesSubscriptionHandle = Meteor.subscribe("project_role_resources");
rateBookRolesSubscriptionHandle = Meteor.subscribe("rate_book_roles");
rateBooksSubscriptionHandle = Meteor.subscribe("rate_books");
rolesSubscriptionHandle = Meteor.subscribe("roles");
Meteor.subscribe("skills");
Meteor.subscribe("resources");
Meteor.subscribe("resource_skills");
Meteor.subscribe("resource_roles");
resourceProjectRolesSubscriptionHandle = Meteor.subscribe("resource_project_roles");
Meteor.subscribe("users");
Meteor.subscribe("fields");
Meteor.subscribe("revenue_projections");