projectsSubscriptionHandle = Meteor.subscribe("projects");
Meteor.subscribe("opportunities");
companiesSubscriptionHandle = Meteor.subscribe("companies");
Meteor.subscribe("contacts");
projectRolesSubscriptionHandle = Meteor.subscribe("project_roles");
Meteor.subscribe("project_role_skills");
rateBookRolesSubscriptionHandle = Meteor.subscribe("rate_book_roles");
rateBooksSubscriptionHandle = Meteor.subscribe("rate_books");
rolesSubscriptionHandle = Meteor.subscribe("roles");
Meteor.subscribe("skills");
Meteor.subscribe("resources");
//Meteor.subscribe("users");
Meteor.subscribe("fields");